name: Build s5 thomas-ca Cours

on:
  push:
    branches:
      - main
    paths:
      - "ressources/s5/thomas-ca/cours/**"

permissions:
  contents: write
  pages: write
  id-token: write

#defaults:
#  run:
#    working-directory: ressources/s5/thomas-ca/tps/ci-cd-symfony

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown to Html
        run: |
          mkdir -p dist/s5/thomas-ca/cours/1_Introduction/
          npx markdown-to-html-cli --source ressources/s5/thomas-ca/cours/1_Introduction/index.md --output dist/s5/thomas-ca/cours/1_Introduction/index.html

      - name: Deploy to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

          rsync -a dist/* ./
          rm -rf dist .astro

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Courses" || echo "No changes to commit"
          git push origin gh-pages
